redhat-exd-rebuilds/estuary-api

purview/__init__.py, purview/utils/general.py, purview/utils/teiid.py, scrapers/koji.py, scripts/scrape.py
Running the scraper script in master was very noisy (it included debug logs from requests, nemodel, etc.). This should fix that.
=> Use a global logger so the logging level can be set at the package level

scrapers/distgit.py
The first commit fixes a bug that occurs when the author or committer is in the wrong format in cgit. The second commit makes the cgit query faster and more efficient.
=> dist-git scraper fixes

scrapers/koji.py
This is nice to have because when the scraper dies due to TEIID going down, we then modify the SQL query to return the last build ID processed and higher to not return already processed data.
=> Order by build.id in the Koji scraper

purview/models/distgit.py, scrapers/distgit.py
Since the Koji scraper can be run before the dist-git scraper, it may create some DistGitCommit nodes in Neo4j since they don't exist yet, but it also doesn't have enough info to fill out the current required properties. Instead, a DistGitCommit node should be able to be created with just the commit hash. The dist-git scraper can then fill out the rest later when it's run.
=> Don't require certain properties on the DistGitCommit model

scrapers/koji.py
Some Git URIs for some reason only have `#` instead of `?#` between the repo and the commit hash.
=> Accept other Git URI formats from Koji build tasks

purview/api/v1.py, purview/models/base.py
This should make it so that we only need one query to get all the direct relationships of a node.
=> Make the resource API more efficient when relationship is True

scrapers/distgit.py
This morning I checked on the scraper run that I started yesterday and the scraper failed because cgit oddly returns a 200 status code for a commit when the repo is empty. This is a workaround for that.
=> Implement a workaround in the dist-git scraper for when a repo is empty

docker/Dockerfile-api, purview/app.py
This will allow us to configure the app in OpenShift via environment variables instead of a config file. This makes passing in secrets easier.
=> Make the configuration more flexible

docker/Dockerfile-api
Install Purview in the Docker image so that the about API endpoint shows the version.
=> Install Purview in the Docker image

scrapers/distgit.py
This should effectively delete the beautiful soup object and all references to it so it doesn't leak memory. If this fails, I will convert the multi-threading to multi-processing.
=> Decompose the beautiful soup after use

estuary/models/koji.py, scrapers/koji.py
I ran into some issue rerunning the Koji scraper and this seems to be the culprit.
=> Stop assuming Koji tag names don't change

estuary/models/base.py, scrapers/freshmaker.py, scrapers/koji.py
Convert existing KojiBuilds to ContainerKojiBuilds if necessary and add another heuristic to determine if a build is a container.
=> Convert existing KojiBuilds to ContainerKojiBuilds if necessary

docker/Dockerfile-api, docker/Dockerfile-scrapers, docker/Dockerfile-tests
Stop pinning the version of python-neo4j-driver since the latest version now works
=> Stop pinning the version of python-neo4j-driver

estuary/api/v1.py, tests/api/test_all_stories.py, tests/api/test_story.py
Adding the "fallback" option will allow the front-end to query the API for a "containerkojibuild" but fallback to a "kojibuild" without having to have the user specify what type of build they are interested in.
=> Add the "fallback" option on the story API endpoints

scrapers/distgit.py
I was still getting OOM errors even after converting to multi-processing. Let's try reducing the chunk size.
=> Reduce the chunk size to 5000 in the dist-git scraper

scrapers/distgit.py
The dist-git scraper stores the results from the Teiid query in the `results` variable. Then it used to run `pool.map` on a method that formatted the results and returned a generator object. The issue is that it seems `pool.map` exhausts the generator right away, causing some data to be duplicated unnecessarily (not sure how much in the results variable and the formatted results point to the same objects in RAM). This may be negligible, but I think it's worth doing to save what we can.
@sarah256 could you please review this?
=> Overwrite results with the formatted results in the dist-git scraper

scrapers/distgit.py
It turns out that using a multiprocess.Pool will reuse the processes rather than
destroy it and create a new one. This makes it so that the memory leak in one of
the libraries is persisting. This commit refactors this so that processes are
terminated after each chunk and created for every chunk processed.
It turns out, the memory consumption is coming from large diffs in cgit. The last commit also addresses that by using a query parameter to stop showing the diff.
=> Refactor the dist-git scraper to not reuse processes while multi-processing

estuary/api/v1.py, tests/api/test_siblings.py
I ran into an issue when trying to request the siblings of container builds that were attached to the same container advisory. This fixes that issue.
=> Fix getting siblings of ContainerAdvisories

docker/Dockerfile-api
Install Estuary with pip so that the no-deps option can be used to not install deps from PyPi if they are missing.
=> Install Estuary with pip so that the no-deps option can be used

docker/Dockerfile-api
Use `setup.py develop --no-deps` instead of `pip3 install . --no-deps` to support dynamic imports used in the `neomodel_install_labels` script that runs after every deployment.
Unfortunately, `setup.py install` can't be used because `--no-deps` is not an option, so `setup.py develop` is used instead. There isn't really any harm in doing this, but it's not ideal.
Alternatively, I could revert to using `setup.py install` but PyPi deps would be pulled in if they were missed during the RPM installation.
=> Use `setup.py develop --no-deps`

estuary/models/freshmaker.py, tests/api/test_all_stories.py, tests/api/test_general.py, tests/api/test_get_resource.py, tests/api/test_relationships.py, tests/api/test_siblings.py, tests/api/test_story.py
Neomodel uses requires attributes as a way to determine if the node exists but we should restrict that to just the FreshmakerEvent ID in the event the data is not filled in entirely from a scraper or estuary-updater handler.
This also removes the useless url parameter
=> Remove some uniqueness and required constraints on the Freshmaker label

estuary/utils/general.py
Fix a key error that would happen if the siblings description was requested for an invalid relationship. I know the error is not as descriptive as it was meant to be but I felt that we should not alter the function parameters to accommodate this error message that should never happen (it's a safe-guard if we have a logic error).
=> Fix a key error

estuary/api/v1.py, tests/api/test_general.py
Since this is no longer used by the front-end, it'd be best to maintain less code and just remove this.
Relates to https://github.com/release-engineering/estuary/pull/62
=> Remove the get_resources API endpoint

scrapers/base.py
So I checked all container builds whose `name` ends with "-container"(21214 builds). Then I checked builds which did not have the `image` attribute in their `extra` among those and found only 6 such builds which were actually rpm builds(pki-core-container each one) example: https://brew.engineering.redhat.com/brew/buildinfo?buildID=741245. 
Then I found out builds not having the `extra` attribute itself and found 769 such builds. I did random checks on few of those builds and turns out they were all built by osbs. Hence, concluding that they are in-fact container builds (example: https://brew.engineering.redhat.com/brew/buildinfo?buildID=676727).
So I think this change should fix the bug of identifying the container builds correctly.
@mprahl Please let me know what you think
=> Add another heuristic to check for container builds

.flake8, docker/Dockerfile-tests, estuary/models/base.py, estuary/models/errata.py, scrapers/base.py, scrapers/errata.py, scrapers/koji.py
The `package` table became ambiguous and caused the scraper to fail. This resolves it.
=> Use unambiguous names when selecting Brew tables

estuary/models/koji.py
Since a single module build now produces a normal build and a "-devel" build, the cardinality no longer applies.
See FACTORY-3453 for context.
=> Remove the cardinality on KojiTag.module_builds

estuary/utils/general.py, tests/api/test_auth.py
Allow employeeType=International Local Hire to see the data in
Estuary, since before it was allowed only to "Employee"s and it
seems that's not enough.
=> Allow International Local Hire to see data

scrapers/koji.py
The diff looks like a lot changed but I really just added `if module_components:` before executing code that assumed it wasn't an empty list.
Take a look at https://github.com/release-engineering/estuary-api/pull/220/files?utf8=%E2%9C%93&diff=split&w=1 for a better diff view.
=> Handle modules without any components

scrapers/freshmaker.py
Some API calls take longer than 15 seconds, so it's best to just increase the timeout.
=> Increase the request timeout to Freshmaker's API in the Freshmaker scraper

estuary/app.py, estuary/config.py, estuary/utils/general.py
Allow the monitoring service, which has the employeeType of `estuary`, to access the Estuary API.
=> Allow the monitoring user to access Estuary

docker/install-ca.sh
In the event the remote server has a certificate with a custom CA, we need to be able to download the CA regardless.
=> Don't validate the CA of the server when downloading the CA

estuary/models/freshmaker.py, scrapers/freshmaker.py
This is important because it changes the way the `serialized_all` method will convert the relationship to JSON. If the cardinality is ZeroOrOne, then `serialized_all` will not use a list to represent this.
=> Set the cardinality on FreshmakerBuild.event

scrapers/freshmaker.py
In the previous PR, I had made a mistake. This line that I'm deleting has a typo in it, but it's not actually needed because of the line below it.
=> Fix a typo in the Freshmaker scraper

estuary/utils/recents.py
This will allow us to see the repos that DistGitCommits are attached to, which the front end needs to know in order to display them.
=> Include the direct relationships of nodes in the recents endpoint

scrapers/freshmaker.py
A recent change introduced the chance to see also failed Freshmaker
builds and not only the successful. Some of them seem to be skipped
due to failure building parent images. With this change they will
also be showed.
ref: FACTORY-4592
Signed-off-by: gnaponie <gnaponie@redhat.com>
=> Show all identified images

scrapers/freshmaker.py
This should fix the traceback:
```
[teiid.py:104:query] Querying Teiid DB "public" with SQL:
--
  | SELECT result
  | FROM brew.task
  | WHERE id = None;
  |  
  | Traceback (most recent call last):
  | File "scripts/scrape.py", line 70, in <module>
  | scraper.run(since=since, until=args.until)
  | File "/src/scrapers/freshmaker.py", line 34, in run
  | self.query_api_and_update_neo4j()
  | File "/src/scrapers/freshmaker.py", line 115, in query_api_and_update_neo4j
  | task_result = self.get_koji_task_result(build_dict['build_id'])
  | File "/src/scrapers/freshmaker.py", line 171, in get_koji_task_result
  | return self.teiid.query(sql=sql_query)[0]['result']
  | File "/src/scrapers/teiid.py", line 116, in query
  | cursor.execute(sql)
  | psycopg2.OperationalError: TEIID31100 Parsing …
```
=> Don't run get_koji_task_result when the Freshmaker build build_id is None

scrapers/errata.py
If replace isn't used, a second relationship is created to the node.
=> Replace existing attached relationships when time_attached is missing or different

estuary/utils/story.py, tests/api/test_timeline.py
Sometimes advisories do not have time data for their associated build(s). We need to be able to catch when this happens so that the processing time can still be calculated, instead of just producing a traceback.
=> Skip advisories with no creation time when calculating processing time

tests/functional/test_BugzillaBug.py, tests/functional/test_ProductVersion.py, tests/infra/test_neo4j.py, tests/requirements.in, tests/requirements.txt, tests/unit/test_ProductVersion.py, tox.ini
There were some flake8-docstrings errors that need to be corrected. This was not caught before because flake8-docstrings was not installed in the tox environment. This is addressed in the second commit.
=> Fix flake8 errors

tests/requirements.in, tests/requirements.txt, tox.ini
Additionally, the test dependencies are not installed
by tox for the isort test. This will speed things up.
=> Run isort by default with tox

docker/Dockerfile-api, docker/Dockerfile-scrapers, docker/Dockerfile-tests
Fedora 30 is not supported anymore and now
that dependencies are installed using PyPi,
the UBI 8 image can be used.
=> Upgrade the base images to use UBI 8

docker/scrape.sh, docs-requirements.txt, requirements.txt, scraper-requirements.txt, scrapers/base.py, scripts/scrape.py, setup.py, tests/requirements.txt
Now that the following PR has been released,
neomodel can be updated to the latest release:
https://github.com/neo4j-contrib/neomodel/pull/553
=> Update neomodel to 4.0.3

scrapers/distgit.py
After the dist-git multiprocessing step, reset the database
connection so that the next scraper doesn't fail with
a `BrokenPipeError` exception.
=> Reset the database connection after multiprocessing

docker/Dockerfile-scrapers
Now that the scrapers install requests from PyPi,
the CA bundle used should be that of the system/container
image.
=> Set the correct requests CA bundle

.travis.yml, README.md
Due to the number of serious security incidents with Travis CI system, moving off Travis CI and probably will setup github actions to run the tests later.
=> Move off Travis CI
