redhat-exd-rebuilds/estuary-api

- purview/models/koji.py
@mprahl I have altered the model for koji as discussed in our call
> Altered model for koji

- purview/utils/general.py
- test-requirements.txt
- tests/utils/test_general.py
- tox.ini
This will be useful for when we parse the `since` input for our scrapers.
> Add a timestamp parsing function

- scrapers/__init__.py
- scrapers/base.py
- scrapers/koji_scraper.py
@mprahl Can you please review this?
> Added Koji Scraper

- scrapers/distgit.py
The version of BeautifulSoup4 in EPEL7 doesn't return anything when using the `string` keyword on `soup.find`.
> Workaround for an issue encounted when using BeautifulSoup4 on EL7

- .flake8
- README.md
- docker/Dockerfile-tests
- purview/api/v1.py
- purview/app.py
- purview/config.py
- purview/error.py
- purview/logger.py
- purview/models/base.py
- purview/models/bugzilla.py
- purview/models/distgit.py
- purview/models/errata.py
- purview/models/freshmaker.py
- purview/models/koji.py
- purview/models/user.py
- purview/utils/general.py
- purview/utils/teiid.py
- scrapers/base.py
- scrapers/bugzilla.py
- scrapers/distgit.py
- scrapers/errata.py
- scrapers/freshmaker.py
- scrapers/koji.py
- scrapers/utils.py
- scripts/run-flask.sh
- tests/conftest.py
- tests/test_api_v1.py
- tests/utils/test_general.py
Review commit by commit for a rundown of the changes made
> Style fixes and documentation

- scrapers/koji.py
> Connect all Koji tags to a Koji build

- purview/api/v1.py
- purview/models/__init__.py
- purview/models/base.py
- purview/models/bugzilla.py
- purview/models/distgit.py
- purview/models/errata.py
- purview/models/freshmaker.py
- purview/models/koji.py
- purview/models/user.py
- purview/utils/general.py
- scrapers/bugzilla.py
- scrapers/distgit.py
- scrapers/errata.py
- scrapers/freshmaker.py
- scrapers/koji.py
- tests/api/test_bugzilla.py
- tests/api/test_story.py
> Fix relationships and cardinality

- purview/api/v1.py
- purview/models/base.py
- purview/utils/general.py
@yashvardhannanavati can you verify if this fixes your bug? If so, I'll clean up the code.
> Support node relationships to other nodes of the same type in serialized.all

- scrapers/bugzilla.py
- scrapers/errata.py
Update bugzilla and errata scrapers to query on last_modified rather than creation_date
> Update bugzilla and errata scrapers to query on last_modified

- scrapers/koji.py
> Only select the needed columns in the Koji scraper

- scripts/scrape.py
This will be useful for when we run this on a cron job while we don't have the UMB listener/updater.
> Add the "--days-ago" option the scraper script

- purview/app.py
- purview/config.py
- tests/test_app.py
The code was mostly copied from WaiverDB.
> Support CORS on the API

- purview/api/v1.py
- tests/api/test_general.py
This will be used for the initial landing page on the frontend.
> Add an API end-point that lists the available resources and their UID

- purview/models/__init__.py
- purview/models/freshmaker.py
- purview/utils/general.py
- scrapers/freshmaker.py
- tests/api/test_general.py
- tests/api/test_get_resource.py
- tests/api/test_story.py
We need this to happen before we deploy to prod.
Related: https://github.com/release-engineering/purview/pull/24
> Rename ContainerBuilds to ContainerBuild

- purview/utils/teiid.py
I encountered this in OpenShift when running on Python 3.6
> Fix an unbound variable exception in the scrapers

- scrapers/distgit.py
This is a backup plan in the event PR #112 doesn't fix the memory leak. Please review this but don't merge until I've deemed PR #112 will not work (currently testing).
> Convert the dist-git scraper to use multiprocessing instead of threading

- estuary/utils/general.py
- scrapers/bugzilla.py
- scrapers/distgit.py
- scrapers/errata.py
- scrapers/koji.py
- tests/utils/test_general.py
This seems to improve the success rates of queries to Teiid but I'm not sure why.
> Use date in SQL queries instead of datetime

- estuary/utils/general.py
- tests/api/test_story.py
This fixes an issue where correlated nodes weren't calculated when the story didn't start with a Bugzilla Bug.
> Fix correlated nodes

- scrapers/distgit.py
This should be a workaround for the memory leak and be a performance boost.
>  Use multi-processing in the dist-git scraper

- scrapers/bugzilla.py
- scrapers/distgit.py
- scrapers/errata.py
- scrapers/freshmaker.py
- scrapers/koji.py
> Order Teiid queries in descending order in the scrapers

- estuary/api/v1.py
- estuary/utils/general.py
- tests/api/test_all_stories.py
- tests/api/test_story.py
This will allow me to easily determine which node is the active node when displaying the story in the frontend
> Add the requested_node_index meta key to the story API

- estuary/api/v1.py
- estuary/utils/general.py
So this hopefully gets rid of all the extra if statements we used to handle ordering of artifacts having multiple labels. For example, a build can have two labels, `KojiBuild` and  `ContainerKojiBuild`. Now, if the user requests for a kojibuild with id 123, and if that build has two labels, then our code can possibly show the build requested by the user as a `ContainerKojiBuild`. Hence, there can be inconsistencies in the output shown by estuary. This PR resolves this problem by comparing the results returned by our Neo4j graph database with a pre-defined story flow order and ensuring expected labels are assigned to their corresponding node.
I hope this helps. Happy reviewing! :)
> Handle label ordering of stories

- estuary/api/v1.py
- estuary/utils/general.py
- tests/api/test_all_stories.py
- tests/api/test_siblings.py
- tests/api/test_story.py
Links to https://projects.engineering.redhat.com/browse/FACTORY-2716
> Get correlated nodes count in the reverse direction as well

- scrapers/koji.py
> Fix incorrect commit creation

- estuary/api/v1.py
- tests/api/test_relationships.py
Relates to FACTORY-2726
This code seems to produce generic but mostly grammatically correct descriptions. We may need to reconsider renaming a few relationships later on.
> Return a description on the relationships table

- estuary/api/v1.py
- estuary/utils/general.py
- estuary/utils/story.py
- tests/api/test_all_stories.py
- tests/api/test_siblings.py
- tests/api/test_story.py
This should only be merged after #191 is merged. 
PS: This will need a rebase after 191 is merged since this one builds on it.
> Support multiple story flows in siblings API endpoint

- scrapers/freshmaker.py
Stop failing the Freshmaker scraper when the connection times out until FACTORY-3955 is resolved
This will keep the scraper OpenShift cron job from being marked as failed all the time.
> Stop failing the Freshmaker scraper

- README.md
- docker/Dockerfile-api
- docker/Dockerfile-scrapers
- docker/Dockerfile-tests
- estuary/authorization.py
- estuary/config.py
- estuary/utils/general.py
- setup.py
- tests/api/test_authorization.py
> Allow an LDAP group to be used as a user whitelist for authorization

- estuary/app.py
This PR does the following (per commit):
* Refactors how environment variables are applied to the configuration
* Allows setting the LDAP configuration values using environment variables
> Allow setting the LDAP configuration values using environment variables

- scrapers/bugzilla.py
> Use the new Bugzilla virtual database in the scrapers

- README.md
- docker/Dockerfile-tests
- estuary/config.py
- estuary/models/__init__.py
- setup.py
Add the type checker in Travis CI
JIRA: https://projects.engineering.redhat.com/browse/CLOUDWF-771
> Add mypy for testing and CI

- .github/workflows/functional.yml
- .gitpod.Dockerfile
- .gitpod.yml
- Makefile
- README.md
- docker-compose.yml
- docker/Dockerfile-api
- docker/Dockerfile-tests
- scripts/run-flask.sh
- tests/functional/test_healthcheck.py
- tests/requirements.txt
Upgrade: neo4j, apoc, api parent image (fedora 32)
> Spin local dev environment with docker-compose

- docker-compose.yml
- tests/functional/test_BugzillaBug.py
> Bumping docker-compose schema file version, pining requirements versions, adding a functional test

- estuary/models/productversion.py
- tests/functional/test_ProductVersion.py
- tests/unit/test_ProductVersion.py
Product Version is the primary filter for container automation data
/cc @mzidek-gh
> ProductVersion model
